apiVersion: v2
name: generic
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: redis
  version: 0.1.0
  repository: file:///opt/source/Devel/SLST/OpenSource/kickstart-helm/chart/redis