apiVersion: v2
name: generic
description: A Helm chart for Kubernetes
type: application
version: 1.1.1
dependencies:
- name: redis-helm
  version: 1.1.1
  repository: "oci://registry-1.docker.io/divyapriyamuthuvel"