apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: sloopstash-{{.Values.global.environment}}-generic
data:
  supervisor-server: |-
    {{- .Files.Get "files/workload/supervisor/conf/server.conf" | nindent 4}}
  server.conf: |-
    {{- .Files.Get (printf "files/workload/redis/%s/conf/server.conf" .Values.global.redis_version) | nindent 4}}
  supervisor.ini: |-
    {{- .Files.Get (printf "files/workload/redis/%s/conf/supervisor.ini" .Values.global.redis_version) | nindent 4}}