apiVersion: batch/v1
kind: Job
metadata:
  name: redis
  namespace: sloopstash-{{.Values.global.environment}}-generic
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 6
  activeDeadlineSeconds: 180
  completionMode: Indexed
  template:
    metadata:
      name: redis
    spec:
      subdomain: redis
      restartPolicy: Never
      containers:
      - name: test
        image: sloopstash/redis:v{{.Values.global.redis_version}}
        imagePullPolicy:  IfNotPresent
        command:
                - /usr/local/bin/redis-cli
                - -h
                - redis.sloopstash-{{.Values.global.environment}}-generic.svc.cluster.local
                - -p
                - "3000"
                - BGSAVE